### ISSUE TITLE
Add new community partner

### ISSUE THREAD

**Issue by lucianomurr** [ngromeconf/ngrome-website#116]
Angular Wroclaw
https://twitter.com/AngularWroclaw
![angular-wroclaw](https://github.com/ngromeconf/ngrome-website/assets/281553/98ba7795-d431-4de2-8f11-c26b920fa34d)

Angular Space
https://www.angularspace.com/
![angular-space](https://github.com/ngromeconf/ngrome-website/assets/281553/53223e0c-5f2b-497c-8540-3c2330d93852)

Latina in Tech
https://www.latinaintech.org/
![latina-in-tech](https://github.com/ngromeconf/ngrome-website/assets/281553/1a7d0f6b-2220-49a8-b927-d2fd432ef149)

**Comment by GMalacaria** [comment]
@lucianomurr  i see that all images are in firebasestorage
can you add this images in firebasestorage? or can you show me how to do it?

**Comment by lucianomurr** [comment]
@GMalacaria 

https://firebasestorage.googleapis.com/v0/b/ngrome-79ce3.appspot.com/o/partner%2Fangular-space-small.webp?alt=media&token=3a61ce50-3459-4518-a728-a044ef3359ea

https://firebasestorage.googleapis.com/v0/b/ngrome-79ce3.appspot.com/o/partner%2Fangular_wroclaw-small.webp?alt=media&token=3074df1f-744e-4b76-a2da-3bf0a1c18252

https://firebasestorage.googleapis.com/v0/b/ngrome-79ce3.appspot.com/o/partner%2Flatina-in-tech.webp?alt=media&token=5206d8a9-1d68-43f5-b1b4-b96350d666cc
