### ISSUE TITLE
Update Opening Keynote details by Alex, Marko & Brandon

### ISSUE THREAD

**Issue by lucianomurr** [ngromeconf/ngrome-website#172]
NgRx Evolution: Exploring the Past, Present, and Future of State Management in Angular

Join us on a journey through the evolution of NgRx state management solutions within the Angular ecosystem. From the initial idea to its current state and future prospects, we'll explore the transformative changes that have shaped NgRx's past, present, and future. Discover the historical context, current best practices, and upcoming innovations that define the landscape of state management in Angular applications.

**Comment by GMalacaria** [comment]
add in Agenda PR
